encryption_key: tlt_encode
results_dir: /results
dataset:
  inference_data: <required>
  num_classes: 1
  batch_size: 1
  workers: 4
inference:
  trt_engine: /results/centerpose.engine
  visualization_threshold: 0.3
  principle_point_x: 298.3225504557292
  principle_point_y: 392.1635182698568
  focal_length_x: 651.2994384765625
  focal_length_y: 651.2994384765625
  skew: 0.0
  axis_size: 0.5
  use_pnp: true
  save_json: true
  save_visualization: true
  opencv: true
