# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repositories:
  - name: nvidia
    url: https://helm.ngc.nvidia.com/nvidia

releases:
  - name: gpu-operator
    namespace: gpu-operator
    chart: nvidia/gpu-operator
    version: v25.10.0
    createNamespace: true
