results_dir: /results
evaluate:
  trt_engine: /results/classification-pyt.engine
  batch_size: 1
model:
  head:
    topk:
    - 1
dataset:
  batch_size: 1
  test_dataset:
    images_dir: /data/images
