encryption_key: tlt_encode
results_dir: /results
model:
  backbone:
    type: fan_small_12_p4_hybrid
  decode_head:
    feature_strides: [4, 8, 16, 32]
dataset:
  segment:
    dataset: SFDataset
    root_dir: /data/segformer
    label_transform: norm
    batch_size: 1
    workers: 4
    num_classes: 2
    img_size: 256
    train_split: train
    validation_split: val
    test_split: val
    predict_split: test
    augmentation:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      random_flip:
        vflip_probability: 0.5
        hflip_probability: 0.5
        enable: true
      random_rotate:
        rotate_probability: 0.5
        angle_list: [90, 180, 270]
        enable: true
      random_color:
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
        hue: 0.3
        enable: false
      with_scale_random_crop:
        enable: true
      with_random_crop: true
      with_random_blur: false
    palette:
    - seg_class: foreground
      rgb: [0, 0, 0]
      label_id: 0
      mapping_class: foreground
    - seg_class: background
      rgb: [1, 1, 1]
      label_id: 1
      mapping_class: background
gen_trt_engine:
  gpu_id: 0
  onnx_file: /models/model.onnx
  trt_engine: /results/segformer.engine
  batch_size: -1
  tensorrt:
    data_type: fp16
    workspace_size: 1024
    min_batch_size: 1
    opt_batch_size: 1
    max_batch_size: 1
