encryption_key: tlt_encode
results_dir: /results
task: classify
inference:
  trt_engine: /results/visual-changenet.engine
  batch_size: 1
model:
  backbone:
    type: c_radio_v2_vit_base_patch16_224
  classify:
    eval_margin: 0.3
    difference_module: learnable
    embed_dec: 30
dataset:
  classify:
    train_dataset:
      csv_path: /data/metadata.csv
      images_dir: /data/images
    validation_dataset:
      csv_path: /data/metadata.csv
      images_dir: /data/images
    test_dataset:
      csv_path: /data/metadata.csv
      images_dir: /data/images
    infer_dataset:
      csv_path: /data/metadata.csv
      images_dir: /data/images
    image_ext: .jpg
    batch_size: 1
    workers: 0
    fpratio_sampling: 0.1
    num_input: 1
    input_map:
      SolderLight: 0
    concat_type: linear
    grid_map:
      x: 2
      y: 2
    image_width: 224
    image_height: 224
    augmentation_config:
      rgb_input_mean:
      - 0.485
      - 0.456
      - 0.406
      rgb_input_std:
      - 0.229
      - 0.224
      - 0.225
