encryption_key: "tlt_encode"
results_dir: "/results"
dataset:
  infer_data_sources:
    image_dir:
      - "/data/infer/images"
    classmap: "/data/infer/label_map.txt"
  num_classes: 91
  batch_size: 1
  workers: 8
  augmentation:
    input_mean: [0.485, 0.456, 0.406]
    input_std: [0.229, 0.224, 0.225]
inference:
  trt_engine: "/results/dino.engine"
  conf_threshold: 0.5
  input_width: 960
  input_height: 544
  color_map: {}
model:
  backbone: resnet_50
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  num_select: 300
  dropout_ratio: 0.0
  dim_feedforward: 2048
