encryption_key: "tlt_encode"
results_dir: "/results"
dataset:
  num_classes: 91
  batch_size: 1
  augmentation:
    input_mean: [0.485, 0.456, 0.406]
    input_std: [0.229, 0.224, 0.225]
model:
  backbone: resnet_50
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 300
  num_select: 300
  dropout_ratio: 0.0
  dim_feedforward: 2048
gen_trt_engine:
  gpu_id: 0
  onnx_file: "/models/model.onnx"
  trt_engine: "/results/dino.engine"
  batch_size: -1
  tensorrt:
    data_type: FP16
    workspace_size: 1024
    min_batch_size: 1
    opt_batch_size: 1
    max_batch_size: 8
    calibration:
      cal_image_dir: []
      cal_cache_file: "/results/dino_calibration.cache"
      cal_batch_size: 1
      cal_batches: 1
