encryption_key: tlt_encode
results_dir: /results
dataset:
  test_data_sources:
    image_dir: /data/images
    json_file: /data/annotations.json
  num_classes: 5
  batch_size: 1
  workers: 8
  eval_class_ids:
  - 1
  - 2
  - 3
  - 4
evaluate:
  trt_engine: /results/rtdetr.engine
  conf_threshold: 0.0
  input_width: 640
  input_height: 640
model:
  backbone: resnet_50
  num_feature_levels: 3
  dec_layers: 6
  enc_layers: 1
  num_queries: 300
  num_select: 300
  dropout_ratio: 0.0
  dim_feedforward: 1024
